### ISSUE TITLE
Call for nominations email

### ISSUE THREAD

**Issue by juanis2112** [numfocus/elections#13]
We need to write an email for the NumFocus community to let them know about the call for nominations for joining the board of directors, with information about the board, how to nominate and relevant deadlines.  If we want to post this also in social media we probably need a shorter version.

I have started [this document](https://docs.google.com/document/d/154V4xwh-rLytzcATjApbAkpS4hYGhpyxJe1hP5hQq3M/edit)

There's more relevant information about this in #4

**Comment by Eldo420** [comment]
Subject: Call for Nominations: Join the NumFOCUS Board of Directors or Election Committee!

Dear NumFOCUS Community,

We are excited to announce that nominations are now open for positions on the NumFOCUS Board of Directors and the Election Committee! We encourage members of our community to participate in shaping the future of NumFOCUS by nominating themselves or other qualified individuals.

**About NumFOCUS:**
NumFOCUS is a nonprofit organization that promotes open practices in research, data, and scientific computing. We support open source projects and ensure their sustainability, fostering an inclusive and dynamic community.

**Available Positions:**
1. **Board of Directors**: As a member of the Board, you will play a vital role in strategic decision-making, helping to guide NumFOCUS's initiatives, and ensuring the long-term success of the organization. Board members typically serve for a term of XX years.
2. **Election Committee**: Members of the Election Committee are responsible for overseeing the election process, maintaining its integrity, and ensuring fair and transparent voting. This role is crucial to our commitment to an inclusive and representative governance structure.

**Qualifications:**
- Passion for open source and the mission of NumFOCUS
- Ability to commit time and effort to the responsibilities of the role
- Experience in governance, community leadership, or project management (for Board of Directors)
- Impartiality and organizational skills (for Election Committee)

**How to Nominate:**
To nominate yourself or another individual, please submit a nomination form [insert link to nomination form here]. The deadline for submission is [insert deadline date here].

**What to Include:**
- Full name of the nominee
- Position being nominated for (Board of Directors or Election Committee)
- Contact information (email and phone number)
- A brief statement (300-500 words) outlining the nominee’s qualifications and vision for NumFOCUS
- [Optional] A CV or resume

**Selection Process:**
The Nominations Committee will review all submissions and create a shortlist of candidates. Shortlisted candidates will be notified via email and may be asked to participate in a brief interview. Final candidates will be presented to the NumFOCUS community for voting in our upcoming election.

**Timeline:**
- Nominations Open: [insert start date here]
- Nominations Close: [insert closing date here]
- Shortlisting of Candidates: [insert dates here]
- Candidate Interviews: [insert dates here]
- Community Voting: [insert dates here]
- Announcement of Results: [insert date here]

We look forward to your nominations and thank you for your continued support and active participation in the NumFOCUS community.

Best regards,

[Your Name]  
[Your Position]  
NumFOCUS Nominations Committee  
[Email Address]  
[Phone Number]  
[Website URL]

---
[Optional: Add disclaimers or additional links, such as to the NumFOCUS governance documents or past election results, if applicable.]

**Comment by pavithraes** [comment]
Thanks for starting this! The email is now complete and will be sent out soon. :)

**Comment by tkoyama010** [comment]
@all-contributors please add @juanis2112 for ideas
