### ISSUE TITLE
Redirection from Election nomination Google Form : leading to 404

### ISSUE THREAD

**Issue by sayantikabanik** [numfocus/elections#18]
Hi Team, 

The hyperlink -> https://github.com/numfocus/elections/blob/initial-docs/board-responsibilities.md from the [Google form](https://docs.google.com/forms/d/1RCua1H_0qjtvzhY4FVchxE1PXBJfgn-IvQ6xZIA2fNI)
currently redirects to an undefined URL.

<img width="474" alt="Screenshot 2024-06-21 at 9 34 36 AM" src="https://github.com/numfocus/elections/assets/17350312/3b28ef44-227a-48e4-a344-1f1ff9a9ad26">

<img width="1440" alt="Screenshot 2024-06-21 at 9 28 51 AM" src="https://github.com/numfocus/elections/assets/17350312/e3e27728-dc1d-454c-a426-8a81b18fe380">

**Comment by tkoyama010** [comment]
@sayantikabanik Thanks. The link has been corrected. Please check it.

**Comment by tkoyama010** [comment]
@all-contributors please add @tkoyama010 for question
