### ISSUE TITLE
Finalize charter

### ISSUE THREAD

**Issue by mrocklin** [numfocus/elections#3]
In [this doc](https://docs.google.com/document/d/1Wr7r_SBjY7yE5-JJEwv20FIcPXHKKeruNG1JM8c419Q/edit) I'm seeing a "combination of the previous two" section at the bottom.  

Are people ok with that section?  I have minor quibbles but in the interests of moving on I'm ready to move on.  If anyone has major issues please raise them here.  In a couple days if there's no major concern I think that we call it done.

**Comment by pavithraes** [comment]
Everyone in the meeting gave a 👍🏼 to the combination. So, unless there are major and/or blocking concerns, we're good to call that final.

**Comment by lsilen** [comment]
The amended version will be submitted to the board and included in the meeting agenda for Friday, March 22. I added this to the end of the committee copy with two edits shown in the comments. https://docs.google.com/document/d/1Wr7r_SBjY7yE5-JJEwv20FIcPXHKKeruNG1JM8c419Q/edit

**Comment by pavithraes** [comment]
Amended version is available here: https://docs.google.com/document/d/1G2PvZhS5mHnT79Y70YSjijEG_G01OQmTjVFeAN6aXJ0/edit#heading=h.uwx9am3who69

Closing this issue as complete :)

**Comment by tkoyama010** [comment]
@all-contributors please add @lsilen for mentoring projectManagement

**Comment by tkoyama010** [comment]
@all-contributors please add @pavithraes for ideas
