### ISSUE TITLE
Solicit nominees

### ISSUE THREAD

**Issue by mrocklin** [numfocus/elections#4]
### From the Board Election Procedure

- NumFOCUS community members will be invited to submit nominations for open board positions. Individuals may self-nominate or nominate someone they feel would be an asset to the organization.
[Draft Nomination Form](https://docs.google.com/forms/d/1RCua1H_0qjtvzhY4FVchxE1PXBJfgn-IvQ6xZIA2fNI/edit) based on the 2021 form - The introduction needs to be rewritten, and the questions reviewed/edited. 
- NumFOCUS Community Members will be defined as all Individuals who have opted in to receive the newsletter, our member and affiliated project lists (sent to project leads who are our NF contacts or, in some cases, the project’s leadership committee), members of NumFOCUS committees, and those on the current events mailing list.
- Nominations will be open for one month.

### Stuff we should do

It seems like we make a simple Google Form (or similar) publish it to various sources (the newsletter, social, word of mouth) probably a few times, and then wait a month.  

My hope is that the lift here isn't that hard.  [Here is an example form submission](https://docs.google.com/forms/d/e/1FAIpQLSdYRlTOyVMvKJh-gr3Zc67zAKGLk5t7Le4ijf3nLV8dXD7p5g/viewform?usp=sharing) (I just spent five minutes making one, we can probably do better than this if we want). 

- [ ] Get some people to review the form above
- [ ] Publish form and background on various channels
- [ ] Re-publish
- [ ] Re-publish

### Places we can post things

- [ ] Newsletter
- [ ] Numfocus Mailing list
- [ ] Twitter / mastodon
- [ ] Slack
- [ ] Prominent projects and their discussion locations (example Pangeo has a discourse forum)
- [ ] ... (help add ideas here)
- [ ] .

Bonus points for places that we think would help us build a more diverse pool of candidates.

**Comment by lagru** [comment]
Thanks for starting with the form. My 2cts for the form:
- Require name & email for both the person nominating and the person being nominated. That way we can reach out to both if we have to.
- Use clearer wordinge.g., "Name of nominee" and "Email of nominee" otherwise it might be ambiguous.

**Comment by mrocklin** [comment]
I'd also like to solicit ideas for where we should broadcast information.  I've edited the top comment to create a list.  I recommend that other people edit that comment as well to add to the list (or just say things in a comment below)

**Comment by mrocklin** [comment]
- John asks: What kind of people are we trying to get to be nominated to the board? Are they only experienced project maintainers etc? Or attendees of local meetups who might be getting involved for the first time? I ask as there's different channels to contact different people, and James mentioned high quality candidates

- James responds: lots of different sides of NumFOCUS.  Wants lots of different kinds of people that reflect those different sides.

- John: What's under-represented?  Where should we focus?
- James: we're low on foundational projects and on new projects, few strong academics, but have some academics generally
- John: we should probably focus there though

- Leah: the board is also intentionally split in function, which reflects some of this distinction.  We want people with operational knowledge, legal background, etc..  This isn't just projects and academics.
- Matt: it's probably important that nominees see the different kinds of backgrounds that are needed, so that they feel possibly qualified

@jaspajjr volunteered to spend a day and hunt down some places where we can broadcast.

**Comment by jaspajjr** [comment]
What methods does NumFocus use to communicate with sponsored projects? Is there a mailing list? Individual contact emails? Something else? Perhaps one for @lsilen ?

**Comment by mrocklin** [comment]
@jaspajjr there's a projects at numfocus.org mailing list that I receive e-mails from that is used for this purpose I think.

**Comment by jaspajjr** [comment]
* NumFocus mailing list
* NumFocus Newsletter
* NumFocus Projects mailing list ( I'm not sure if this is different)
* Twitter - NumFocus & PyData accounts, are there other appropriate accounts we could use?
* Mastodon
* NumFocus Slack
* PyData Slack
* PyData Meetup messaging system
* Open Source Science

I propose we use these channels of communication. While some of these channels can be used by any member (such as slack) It's worth identifying who has access to Twitter / Mastadon / Meetup accounts and the various mailing lists.

**Comment by mrocklin** [comment]
Going one level deeper, probably each of the projects has their own place for conversations.  For example in Dask we have a discourse forum and a github.com/dask/community issue tracker where it might be appropriate to advertise stuff like this.  For Pangeo we have https://discourse.pangeo.io/ which is pretty active.  

I suspect that we could get a little pushy and either ask project maintainers for these locations, or just hunt them down ourselves by going to the docs of each project.  Probably finding all of the locations is a few hours of work.  

A less demanding (but also probably less effective) route would be to arm the maintainers with language of their own that they could post in the right location on our behalf.  Probably arming them with language makes it more likely that they'll help out (less work on their part?).

**Comment by lsilen** [comment]
We have a Sponsored and an Affiliated Project google group, so we can send to both. 
I'll ask Arliss if she has a list of the project communication channels.

**Comment by jaspajjr** [comment]
If Arliss doesn't have a list then let me know, and I'll go through the documentation for the projects and create one

**Comment by lsilen** [comment]
Arliss said she doesn't have a list but could create one. @jaspajjr, have you started creating one? We don't want to duplicate work!

**Comment by jaspajjr** [comment]
I haven't yet, I was waiting to hear back

**Comment by arliss-NF** [comment]
I have started a list - will be finished by EOW - is it needed sooner?

**Comment by pavithraes** [comment]
Closing as completed now that we have a set of nominees :)
