### ISSUE TITLE
Discussion: Who can vote and how?

### ISSUE THREAD

**Issue by pavithraes** [numfocus/elections#51]
We're discussing who will get to vote in the elections, and will appreciate any thoughts and inputs from the community.

## Background

In the [board procedures document](https://docs.google.com/document/d/18hCD0ZPQCv-KgN-L9V-fGs6gQqdFm4Xm4TzqzThUSkA/edit?usp=sharing) shared by the Board, the following voting groups were identified:

> NF member projects - 3 votes
> NF Affiliated projects - 1 vote
> NF Committee Officers - 1 vote
> Event Chairs - 1 vote

With the expectation that sponsored & affiliated projects will self organize to cast their votes.

This list is intended to represent all community stakeholders. The sponsored projects are the core stakeholders, and hence their votes are weighted higher _(i.e., as 3 votes)._

We'd like to maintain this overall share: Sponsored projects represent have 50% of total votes, affiliate projects - 25%, and  committees, and events represent 12-13% each.

### Concerns with the original groups

The projects vote as a group, while committee officers & event chairs get individual votes.

Sometimes, the officers and chairs are also a part of sponsored & affiliated projects, and we'll have to trust that they vote representing their committee/events and not their projects. 

### Option 2: Only group-votes

We can have votes only per-group, i.e., committees and events also vote as a group.

In this case, the total number of committees and events are small, so we will need to _weight_ their votes as 2 or 3 votes to get the right vote share split.

Note that event groups are only active during the planning & running of events, so expecting them to coordinate and vote as a group is not ideal.

### Option 3: Only individual-votes

We can have specific individuals representing sponsored and affiliated projects cast votes.

The best way to ensure this is to run a voter registration drive, where we ask all groups to register voting members. This will be tricky and take more time.

Individuals will need to mention the specific project or group they represent while registering to vote. If a person is involved in different groups (for instance, a sponsored project and event chair), they need to select one group to represent in the voting process.

#### Options 3.a

Projects can discuss and register a specific number of voting members (3 for sponsored projects & 1 for affiliated projects)

#### Option 3.b -- **Selected ✅** 

Any number of individuals can vote per project, we can then normalize and weight the votes using the voting tool.

For example, if `5` individuals vote from `my_awesome_sponsored_project`, each vote will be weighted as `3/5` because `my_awesome_sponsored_project` as a whole gets 3 votes as a sponsored project.

**Comment by tkoyama010** [comment]
@all-contributors please add @pavithraes for question

**Comment by tkoyama010** [comment]
@all-contributors please add @pavithraes for question

**Comment by pavithraes** [comment]
We've **decided to go with Option 3.b** described above.

This was chosen because:
- In option 2, coordinating to cast votes as a group (for projects or committees) can be very difficult, especially since we're also planning to do ranked-choice voting, which involves `ranking` the selected nominees in addition to `selecting` them. 
- In option 3.a, the responsibility for selecting voting members will be on the projects, which will also require coordination & discussions. In large projects, selecting these voting individuals might even need an internal vote.

We want to include as many community members as possible in the voting process, while also ensuring all projects in a group (i.e, sponsored & affiliated) have equal say. We also want the voting process to be lightweight for the community members, to encourage participation. Hence, Option 3.b was decided as the most equitable.

We're always open to more feedback, please let us know if you have thoughts and ideas.
