### ISSUE TITLE
Register Astropy Voters

### ISSUE THREAD

**Issue by ceb8** [numfocus/elections#65]
Hi!

Astropy as decided to open the election to all of our voting members who want to be included in our weighted tally. What is the best way to go about getting them registered? Can I give the election committee a list of names and emails?

Thanks!

**Comment by pavithraes** [comment]
Thanks for your question, you can share the voter registration link (sent it to you on Slack) with all your members who'd like to participate. They can select Astropy in the project selection section. :)

**Comment by ceb8** [comment]
For any voting member from Astropy seeing this: you have alll been registered for this election, there is no need to take individual action.
