### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by mrocklin** [numfocus/elections#8]
In order to start elections I think that we need to: 

1.  Explain what's going on #5 
2. Create some sort of form for nominations
3. Broadcast the explanation of what's going on and the form to all relevant parties #4 

We're on a clock here.  Current board members would like to roll off.  We haven't yet had much momentum, but we could!  What can people commit to? 

@lagru can you push #5 to a point where we're proud and think that it'll do a good job converting people?

@jaspajjr if we're ready to go do you think you could lead the charge on broadcasting things?

Are other people in the committee able to push this forward?

**Comment by jaspajjr** [comment]
Sorry I'm rather pressed for time at the moment, I'm conscious that this week we're [waiting for Arliss](https://github.com/numfocus/elections/issues/4#issuecomment-2045238355) before we can make a start. I'm willing to try my best, but I don't want to commit to something I may not be able to deliver

**Comment by lsilen** [comment]
The committee can move forward soliciting nominees through the project google groups (Sponsored and Affiliated Projects), the NF mailing list, the list of NF committee members, and the list of event organizers. NF staff can help and projects can be asked to post the information and form on their mailing lists.

**Comment by pavithraes** [comment]
Nominations and elections are now complete, closing :)
